### ISSUE TITLE
Increase speed in the backward direction.

### ISSUE THREAD

**Issue by fig-shimooka** [ezWheelSAS/swd_ros_controllers#12]
I want to increase the speed of the SWD Core in the back direction.
Is there a way to do this?

**Comment by ez-Support** [comment]
As there is no laser scanner watching StarterKit's back, a SLS is acctivated when moving backward.
You should increase the SLS speed in the commissioning script to do so (e.g. sls_vl_limit = 1000).

**Comment by fig-shimooka** [comment]
LaserScanner will be added behind SWD Core.
In this case, will the speed increase without changing the SLS?
Does it have the same speed as going forward?

**Comment by ez-Support** [comment]
No if you change the SLS speed in the commissioning, it will reduce it.
The maximum speed of the SWD is 1800 RPM.

**Comment by ez-Support** [comment]
You have indeed in that case to modify the launch file of the **swd_diff_drive_controller.launch**, in the field :
`<rosparam param="have_backward_sls">false</rosparam>` change false to true.
You should then restart services

**Comment by fig-shimooka** [comment]
I want to go backwards at the same speed as forwards.
If I set have_backward_sls to True, will my wish be fulfilled?

**Comment by ez-Support** [comment]
Yes !

**Comment by fig-shimooka** [comment]
Thank you!
I'll try to follow your advice.

**Comment by ez-Support** [comment]
You can `roscd swd_ros_controllers/launch/` to get directly to the directory 👍

**Comment by ez-Support** [comment]
Did you successfully resolved the issue ?

**Comment by fig-shimooka** [comment]
Sorry for the late reply.
I am now checking the SWDCore backward .
Both forward and backward travel was at the same speed.
However, if I back up with an obstacle behind me, it does not slow down when I get close to it.
When moving forward, the vehicle decelerates when an obstacle is approaching.

starter_kit.launch
```
<?xml version="1.0"?>
<launch>
  <arg name="master_ip" value="192.168.0.1" />
  <arg name="laser1_sensor_ip" value="192.168.0.110" />
  <arg name="laser2_sensor_ip" value="192.168.0.111" />
  <arg name="laser1_prefix" value="laser_1" />
  <arg name="laser2_prefix" value="laser_2" />
  <arg name="joy_config" value="xbox" />

  <!-- EZW ROS Controllers (diff-drive) -->
  <include file="$(find swd_ros_controllers)/launch/swd_diff_drive_controller.launch"/>

  <!-- IDEC -->
  <node pkg="urg_node" name="urg_node_1" type="urg_node">
    <param name="ip_address" value="$(arg laser1_sensor_ip)" />
    <param name="frame_id" value="$(arg laser1_prefix)" />
    <param name="angle_min" value="-1.5707963"/>
    <param name="angle_max" value="1.5707963"/>
    <remap from="/scan" to="/$(arg laser1_prefix)/scan" />
  </node>

  <node pkg="urg_node" name="urg_node_2" type="urg_node">
    <param name="ip_address" value="$(arg laser2_sensor_ip)" />
    <param name="frame_id" value="$(arg laser2_prefix)" />
    <param name="angle_min" value="-1.5707963"/>
    <param name="angle_max" value="1.5707963"/>
    <remap from="/scan" to="/$(arg laser1_prefix)/scan" />
  </node>

  <!-- <node pkg="tf" type="static_transform_publisher" name="laser_broadcaster" args="0.04 0 0 0 0 0 base_link laser_1 100" /> -->
  <!-- /IDEC -->

  <!--
  <include file="$(dirname)/mapping_lama.launch"/>
  -->

  <!-- <include file="$(dirname)/mapping_hector.launch"/>
  -->
  <!--
  <node pkg="tf" type="static_transform_publisher" name="map_odom_broadcaster" args="0 0 0 0 0 0 odom base_link 100"/>
  -->

  <!-- Websocket bridge (for HMI) -->
  <!--
  <node pkg="rosbridge_server" name="rosbridge_websocket" type="rosbridge_websocket">
    <param name="address" value="$(arg master_ip)" />
    <param name="use_compression" value="true" />
  </node>
  -->
  <!--
  <node pkg="tf2_web_republisher" name="tf2_web_republisher" type="tf2_web_republisher" />
  -->

  <!-- Joystick + teleop -->
  <node pkg="joy" name="xbox_joystick" type="joy_node">
    <param name="autorepeat_rate" value="50" />
     <remap from="/joy" to="/joy/id0/joy" />
  </node>
<!-- 
  <node pkg="teleop_twist_joy" name="teleop_twist_joy"
  type="teleop_node">
    <param name="joy_config" value="$(arg joy_config)" />
    <param name="enable_button" value="5" />
    <param name="enable_turbo_button" value="6" />
    <param name="axis_linear" value="1" />
    <param name="axis_angular" value="3" />
    <param name="scale_linear" value="1.0" />
    <param name="scale_angular" value="0.7" />
    <param name="scale_linear_turbo" value="1.3" />
    <param name="scale_angular_turbo" value="1.4" />
     <remap from="/cmd_vel" to="/swd_diff_drive_controller/cmd_vel" />
  </node> -->

  <!-- Robot manager -->
  <!--
  <node pkg="swd_robot_manager" name="robot_manager" type="robot_manager" />
  -->
</launch>

```

**Comment by ez-Support** [comment]
So if I sum-up, you have 2 laser scanners. The 1st one is watching forward and the 2nd one backward.
When an obstacle is detected forward, SLS is activated on the front laser scanner, and the robot reduces the speed.
When an obstacle is detected backward, SLS is activated on the back scanner, but the robot does not reduces its speed.

Is that it ?

Then, I would suggest:

1. Make sure, you have commissionned the SLS function on the SWD Core with the back scanner. 
I guess on the right SWD Core, so you should have added on swd_right_5_commissioning.py:
```
scw = SafetyControlWordId.SAFEIN_1
scwMapping = [
    SafetyFunctionId.NONE,
    SafetyFunctionId.NONE,
    SafetyFunctionId.NONE,
    SafetyFunctionId.NONE,
    SafetyFunctionId.NONE,
    SafetyFunctionId.NONE,
]

scwMapping[0] = SafetyFunctionId.SLS_1
scwMapping[1] = SafetyFunctionId.SLS_1
```
2. When SLS-OSSD is active on the back scanner, what is the status of `safety_limited_speed` in the safety topic ? 
(e.g. `rostopic echo /swd_diff_drive_controller/safety`)

**Comment by fig-shimooka** [comment]
Yes, that is correct.
Apparently the back scanner limits the speed in the forward direction when SLS is enabled.
I would speculate that you may need to set which scanner is behind you.

When there are no obstacles
```
header: 
  seq: 8230
  stamp: 
    secs: 1649933155
    nsecs: 671764454
  frame_id: "base_footprint"
safe_torque_off: False
safe_brake_control: False
safety_limited_speed: True
safe_direction_indication_forward: False
safe_direction_indication_backward: False

```


When there is an obstacle behind you.
```
---
header: 
  seq: 7626
  stamp: 
    secs: 1649933034
    nsecs: 871452233
  frame_id: "base_footprint"
safe_torque_off: False
safe_brake_control: False
safety_limited_speed: True
safe_direction_indication_forward: True
safe_direction_indication_backward: False
```

**Comment by fig-shimooka** [comment]
SDI is also only applied in the forward direction.

**Comment by ez-Support** [comment]
You did configure a SDI on the SE2l back laser too? With  the same configuration as the front laser ?
If so, you need to configure it to in the commissionning scripts:

- swd_left_4_commissioning.py:
```
    scw = SafetyControlWordId.CAN_2
    scwMapping = [
        SafetyFunctionId.NONE,
        SafetyFunctionId.NONE,
        SafetyFunctionId.NONE,
        SafetyFunctionId.NONE,
        SafetyFunctionId.NONE,
        SafetyFunctionId.NONE,
        SafetyFunctionId.NONE,
        SafetyFunctionId.NONE,
    ]
    scwMapping[0] = SafetyFunctionId.STO
    scwMapping[1] = SafetyFunctionId.STO
    scwMapping[2] = SafetyFunctionId.SDIP_1
    scwMapping[3] = SafetyFunctionId.SDIP_1
    scwMapping[4] = SafetyFunctionId.SLS_1
    scwMapping[5] = SafetyFunctionId.SLS_1

```
-     And on swd_right_5_commissioning.py:
```
    scw = SafetyControlWordId.SAFEIN_1
    scwMapping = [
        SafetyFunctionId.NONE,
        SafetyFunctionId.NONE,
        SafetyFunctionId.NONE,
        SafetyFunctionId.NONE,
        SafetyFunctionId.NONE,
        SafetyFunctionId.NONE,
    ]
    scwMapping[0] = SafetyFunctionId.STO
    scwMapping[1] = SafetyFunctionId.STO
    scwMapping[2] = SafetyFunctionId.SDIN_1
    scwMapping[3] = SafetyFunctionId.SDIN_1
    scwMapping[4] = SafetyFunctionId.SLS_1
    scwMapping[5] = SafetyFunctionId.SLS_1
```

**Comment by fig-shimooka** [comment]
COMMISSIONING was carried out with its contents.
OSSD is no longer enabled and no backing is possible at all.
Do I need to configure the SE2L side to enable SLS and SDI on the SE2L behind?

```
header: 
  seq: 807
  stamp: 
    secs: 1650013151
    nsecs: 475671319
  frame_id: "base_footprint"
safe_torque_off: False
safe_brake_control: False
safety_limited_speed: True
safe_direction_indication_forward: False
safe_direction_indication_backward: True

```

**Comment by ez-Support** [comment]
I might have inverted SDIP_1 and SDIN_1 maybe.
To configure the SE2L scanner you need to download SLS designer from IDEC website.
You can download the configuring file (.hucx) from our github or you will also find it in the commissioning folder of the starter kit

**Comment by fig-shimooka** [comment]
SDIP_1 and SDIN_1 were swapped.
As a result, now I cannot move forward, even though all OSSDs are not working.

I am also concerned that safety_limited_speed is always True.

There was only one SLS designer configuration file on github.
How should I configure it if I want to attach it in the front/back direction .
Currently, the forward SE2L is set to master and the number of slaves to 1 in the master-slave item of the SLS designer.
The SE2L behind is set to slave 1.

```
header:
  seq: 2250
  stamp:
    secs: 1650243261
    nsecs: 905151305
  frame_id: "base_footprint"
safe_torque_off: False
safe_brake_control: False
safety_limited_speed: True
safe_direction_indication_forward: True
safe_direction_indication_backward: False
```
